// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface ArticleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.Article)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant_id = 1;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 1;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string thumb = 4;</code>
   * @return The thumb.
   */
  java.lang.String getThumb();
  /**
   * <code>string thumb = 4;</code>
   * @return The bytes for thumb.
   */
  com.google.protobuf.ByteString
      getThumbBytes();

  /**
   * <code>string out_link = 6;</code>
   * @return The outLink.
   */
  java.lang.String getOutLink();
  /**
   * <code>string out_link = 6;</code>
   * @return The bytes for outLink.
   */
  com.google.protobuf.ByteString
      getOutLinkBytes();

  /**
   * <code>uint64 views = 7;</code>
   * @return The views.
   */
  long getViews();

  /**
   * <code>string icon = 5;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>string icon = 5;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>string keywords = 8;</code>
   * @return The keywords.
   */
  java.lang.String getKeywords();
  /**
   * <code>string keywords = 8;</code>
   * @return The bytes for keywords.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes();

  /**
   * <code>string category_id = 9;</code>
   * @return The categoryId.
   */
  java.lang.String getCategoryId();
  /**
   * <code>string category_id = 9;</code>
   * @return The bytes for categoryId.
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>string status = 10;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 10;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string creator_id = 11;</code>
   * @return The creatorId.
   */
  java.lang.String getCreatorId();
  /**
   * <code>string creator_id = 11;</code>
   * @return The bytes for creatorId.
   */
  com.google.protobuf.ByteString
      getCreatorIdBytes();

  /**
   * <code>string updater_id = 12;</code>
   * @return The updaterId.
   */
  java.lang.String getUpdaterId();
  /**
   * <code>string updater_id = 12;</code>
   * @return The bytes for updaterId.
   */
  com.google.protobuf.ByteString
      getUpdaterIdBytes();

  /**
   * <code>string created_at = 13;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 13;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>string updated_at = 14;</code>
   * @return The updatedAt.
   */
  java.lang.String getUpdatedAt();
  /**
   * <code>string updated_at = 14;</code>
   * @return The bytes for updatedAt.
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();

  /**
   * <code>string deleted_at = 15;</code>
   * @return The deletedAt.
   */
  java.lang.String getDeletedAt();
  /**
   * <code>string deleted_at = 15;</code>
   * @return The bytes for deletedAt.
   */
  com.google.protobuf.ByteString
      getDeletedAtBytes();

  /**
   * <code>string remark = 16;</code>
   * @return The remark.
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 16;</code>
   * @return The bytes for remark.
   */
  com.google.protobuf.ByteString
      getRemarkBytes();

  /**
   * <code>string sort = 17;</code>
   * @return The sort.
   */
  java.lang.String getSort();
  /**
   * <code>string sort = 17;</code>
   * @return The bytes for sort.
   */
  com.google.protobuf.ByteString
      getSortBytes();
}
