// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface ArticleDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.ArticleData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *文章id
   * </pre>
   *
   * <code>int64 article_id = 2;</code>
   * @return The articleId.
   */
  long getArticleId();

  /**
   * <pre>
   *内容
   * </pre>
   *
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   *内容
   * </pre>
   *
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   *是否允许评论
   * </pre>
   *
   * <code>bool allow_comment = 4;</code>
   * @return The allowComment.
   */
  boolean getAllowComment();

  /**
   * <pre>
   *来源
   * </pre>
   *
   * <code>string copy_from = 5;</code>
   * @return The copyFrom.
   */
  java.lang.String getCopyFrom();
  /**
   * <pre>
   *来源
   * </pre>
   *
   * <code>string copy_from = 5;</code>
   * @return The bytes for copyFrom.
   */
  com.google.protobuf.ByteString
      getCopyFromBytes();
}
