// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public final class CmsOuterClass {
  private CmsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_Category_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_Category_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_Article_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_Article_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ArticleData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ArticleData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_CreateCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_CreateCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_CreateCategoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_CreateCategoryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_UpdateCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_UpdateCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_UpdateCategoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_UpdateCategoryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_DeleteCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_DeleteCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_DeleteCategoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_DeleteCategoryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_GetCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_GetCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_GetCategoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_GetCategoryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListCategoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListCategoryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_CreateArticleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_CreateArticleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_CreateArticleReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_CreateArticleReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_UpdateArticleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_UpdateArticleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_UpdateArticleReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_UpdateArticleReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_DeleteArticleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_DeleteArticleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_DeleteArticleReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_DeleteArticleReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_GetArticleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_GetArticleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_GetArticleReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_GetArticleReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListArticleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListArticleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListArticleReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListArticleReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListCategoryByPidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListCategoryByPidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListCategoryByPidReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListCategoryByPidReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListArticleByCidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListArticleByCidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_ListArticleByCidReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_ListArticleByCidReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_GetArticleDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_GetArticleDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_cms_service_v1_GetArticleDataReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_cms_service_v1_GetArticleDataReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcms.proto\022\022api.cms.service.v1\032 google/" +
      "protobuf/field_mask.proto\"\266\002\n\010Category\022\021" +
      "\n\ttenant_id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\023\n\013desc" +
      "ription\030\003 \001(\t\022\r\n\005thumb\030\004 \001(\t\022\020\n\010out_link" +
      "\030\006 \001(\t\022\r\n\005views\030\007 \001(\004\022\014\n\004icon\030\005 \001(\t\022\020\n\010k" +
      "eywords\030\010 \001(\t\022\021\n\tparent_id\030\t \001(\t\022\016\n\006stat" +
      "us\030\n \001(\t\022\022\n\ncreator_id\030\013 \001(\t\022\022\n\nupdater_" +
      "id\030\014 \001(\t\022\022\n\ncreated_at\030\r \001(\t\022\022\n\nupdated_" +
      "at\030\016 \001(\t\022\022\n\ndeleted_at\030\017 \001(\t\022\016\n\006remark\030\020" +
      " \001(\t\022\014\n\004sort\030\021 \001(\t\"\267\002\n\007Article\022\021\n\ttenant" +
      "_id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030" +
      "\003 \001(\t\022\r\n\005thumb\030\004 \001(\t\022\020\n\010out_link\030\006 \001(\t\022\r" +
      "\n\005views\030\007 \001(\004\022\014\n\004icon\030\005 \001(\t\022\020\n\010keywords\030" +
      "\010 \001(\t\022\023\n\013category_id\030\t \001(\t\022\016\n\006status\030\n \001" +
      "(\t\022\022\n\ncreator_id\030\013 \001(\t\022\022\n\nupdater_id\030\014 \001" +
      "(\t\022\022\n\ncreated_at\030\r \001(\t\022\022\n\nupdated_at\030\016 \001" +
      "(\t\022\022\n\ndeleted_at\030\017 \001(\t\022\016\n\006remark\030\020 \001(\t\022\014" +
      "\n\004sort\030\021 \001(\t\"h\n\013ArticleData\022\n\n\002id\030\001 \001(\003\022" +
      "\022\n\narticle_id\030\002 \001(\003\022\017\n\007content\030\003 \001(\t\022\025\n\r" +
      "allow_comment\030\004 \001(\010\022\021\n\tcopy_from\030\005 \001(\t\"Z" +
      "\n\025CreateCategoryRequest\022\021\n\ttenant_id\030\001 \001" +
      "(\t\022.\n\010category\030\002 \001(\0132\034.api.cms.service.v" +
      "1.Category\"-\n\023CreateCategoryReply\022\n\n\002ok\030" +
      "\001 \001(\010\022\n\n\002id\030\002 \001(\003\"\212\001\n\025UpdateCategoryRequ" +
      "est\022\021\n\ttenant_id\030\001 \001(\t\022.\n\010category\030\002 \001(\013" +
      "2\034.api.cms.service.v1.Category\022.\n\nfield_" +
      "mask\030\003 \001(\0132\032.google.protobuf.FieldMask\"E" +
      "\n\023UpdateCategoryReply\022.\n\010category\030\001 \001(\0132" +
      "\034.api.cms.service.v1.Category\"*\n\025DeleteC" +
      "ategoryRequest\022\021\n\ttenant_id\030\001 \001(\t\"\025\n\023Del" +
      "eteCategoryReply\"\'\n\022GetCategoryRequest\022\021" +
      "\n\ttenant_id\030\001 \001(\t\"B\n\020GetCategoryReply\022.\n" +
      "\010category\030\001 \001(\0132\034.api.cms.service.v1.Cat" +
      "egory\"(\n\023ListCategoryRequest\022\021\n\ttenant_i" +
      "d\030\001 \001(\t\"\300\001\n\021ListCategoryReply\022\017\n\007page_no" +
      "\030\001 \001(\003\022\021\n\tpage_size\030\002 \001(\003\022*\n\004list\030\003 \003(\0132" +
      "\034.api.cms.service.v1.Category\022\022\n\ntotal_s" +
      "ize\030\004 \001(\003\022\022\n\ntotal_page\030\005 \001(\004\0223\n\017show_fi" +
      "eld_mask\030\006 \001(\0132\032.google.protobuf.FieldMa" +
      "sk\"W\n\024CreateArticleRequest\022\021\n\ttenant_id\030" +
      "\001 \001(\t\022,\n\007article\030\002 \001(\0132\033.api.cms.service" +
      ".v1.Article\"3\n\022CreateArticleReply\022\021\n\tten" +
      "ant_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\"\216\001\n\024UpdateArtic" +
      "leRequest\022\021\n\ttenant_id\030\001 \001(\t\022,\n\007article\030" +
      "\002 \001(\0132\033.api.cms.service.v1.Article\0225\n\021up" +
      "date_field_mask\030\003 \001(\0132\032.google.protobuf." +
      "FieldMask\" \n\022UpdateArticleReply\022\n\n\002ok\030\001 " +
      "\001(\010\"6\n\024DeleteArticleRequest\022\021\n\ttenant_id" +
      "\030\001 \001(\t\022\013\n\003ids\030\002 \001(\t\" \n\022DeleteArticleRepl" +
      "y\022\n\n\002ok\030\001 \001(\010\"g\n\021GetArticleRequest\022\021\n\tte" +
      "nant_id\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\0223\n\017show_field_" +
      "mask\030\003 \001(\0132\032.google.protobuf.FieldMask\"t" +
      "\n\017GetArticleReply\022,\n\007article\030\001 \001(\0132\033.api" +
      ".cms.service.v1.Article\0223\n\017show_field_ma" +
      "sk\030\002 \001(\0132\032.google.protobuf.FieldMask\"\\\n\022" +
      "ListArticleRequest\022\021\n\ttenant_id\030\001 \001(\t\0223\n" +
      "\017show_field_mask\030\002 \001(\0132\032.google.protobuf" +
      ".FieldMask\"\276\001\n\020ListArticleReply\022\017\n\007page_" +
      "no\030\001 \001(\003\022\021\n\tpage_size\030\002 \001(\003\022)\n\004list\030\003 \003(" +
      "\0132\033.api.cms.service.v1.Article\022\022\n\ntotal_" +
      "size\030\004 \001(\003\022\022\n\ntotal_page\030\005 \001(\004\0223\n\017show_f" +
      "ield_mask\030\006 \001(\0132\032.google.protobuf.FieldM" +
      "ask\"u\n\030ListCategoryByPidRequest\022\021\n\ttenan" +
      "t_id\030\001 \001(\t\022\021\n\tparent_id\030\002 \001(\t\0223\n\017show_fi" +
      "eld_mask\030\003 \001(\0132\032.google.protobuf.FieldMa" +
      "sk\"\305\001\n\026ListCategoryByPidReply\022\017\n\007page_no" +
      "\030\001 \001(\003\022\021\n\tpage_size\030\002 \001(\003\022*\n\004list\030\003 \003(\0132" +
      "\034.api.cms.service.v1.Category\022\022\n\ntotal_s" +
      "ize\030\004 \001(\003\022\022\n\ntotal_page\030\005 \001(\004\0223\n\017show_fi" +
      "eld_mask\030\006 \001(\0132\032.google.protobuf.FieldMa" +
      "sk\"v\n\027ListArticleByCidRequest\022\021\n\ttenant_" +
      "id\030\001 \001(\t\022\023\n\013category_id\030\002 \001(\t\0223\n\017show_fi" +
      "eld_mask\030\003 \001(\0132\032.google.protobuf.FieldMa" +
      "sk\"\303\001\n\025ListArticleByCidReply\022\017\n\007page_no\030" +
      "\001 \001(\003\022\021\n\tpage_size\030\002 \001(\003\022)\n\004list\030\003 \003(\0132\033" +
      ".api.cms.service.v1.Article\022\022\n\ntotal_siz" +
      "e\030\004 \001(\003\022\022\n\ntotal_page\030\005 \001(\004\0223\n\017show_fiel" +
      "d_mask\030\006 \001(\0132\032.google.protobuf.FieldMask" +
      "\"k\n\025GetArticleDataRequest\022\021\n\ttenant_id\030\001" +
      " \001(\t\022\n\n\002id\030\002 \001(\003\0223\n\017show_field_mask\030\003 \001(" +
      "\0132\032.google.protobuf.FieldMask\"\201\001\n\023GetArt" +
      "icleDataReply\0225\n\014article_data\030\001 \001(\0132\037.ap" +
      "i.cms.service.v1.ArticleData\0223\n\017show_fie" +
      "ld_mask\030\002 \001(\0132\032.google.protobuf.FieldMas" +
      "k2\225\n\n\003Cms\022d\n\016CreateCategory\022).api.cms.se" +
      "rvice.v1.CreateCategoryRequest\032\'.api.cms" +
      ".service.v1.CreateCategoryReply\022d\n\016Updat" +
      "eCategory\022).api.cms.service.v1.UpdateCat" +
      "egoryRequest\032\'.api.cms.service.v1.Update" +
      "CategoryReply\022d\n\016DeleteCategory\022).api.cm" +
      "s.service.v1.DeleteCategoryRequest\032\'.api" +
      ".cms.service.v1.DeleteCategoryReply\022[\n\013G" +
      "etCategory\022&.api.cms.service.v1.GetCateg" +
      "oryRequest\032$.api.cms.service.v1.GetCateg" +
      "oryReply\022^\n\014ListCategory\022\'.api.cms.servi" +
      "ce.v1.ListCategoryRequest\032%.api.cms.serv" +
      "ice.v1.ListCategoryReply\022m\n\021ListCategory" +
      "ByPid\022,.api.cms.service.v1.ListCategoryB" +
      "yPidRequest\032*.api.cms.service.v1.ListCat" +
      "egoryByPidReply\022a\n\rCreateArticle\022(.api.c" +
      "ms.service.v1.CreateArticleRequest\032&.api" +
      ".cms.service.v1.CreateArticleReply\022a\n\rUp" +
      "dateArticle\022(.api.cms.service.v1.UpdateA" +
      "rticleRequest\032&.api.cms.service.v1.Updat" +
      "eArticleReply\022a\n\rDeleteArticle\022(.api.cms" +
      ".service.v1.DeleteArticleRequest\032&.api.c" +
      "ms.service.v1.DeleteArticleReply\022X\n\nGetA" +
      "rticle\022%.api.cms.service.v1.GetArticleRe" +
      "quest\032#.api.cms.service.v1.GetArticleRep" +
      "ly\022d\n\016GetArticleData\022).api.cms.service.v" +
      "1.GetArticleDataRequest\032\'.api.cms.servic" +
      "e.v1.GetArticleDataReply\022[\n\013ListArticle\022" +
      "&.api.cms.service.v1.ListArticleRequest\032" +
      "$.api.cms.service.v1.ListArticleReply\022j\n" +
      "\020ListArticleByCid\022+.api.cms.service.v1.L" +
      "istArticleByCidRequest\032).api.cms.service" +
      ".v1.ListArticleByCidReplyB2\n\022api.cms.ser" +
      "vice.v1P\001Z\032rchd/api/cms/service/v1;v1b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.FieldMaskProto.getDescriptor(),
        });
    internal_static_api_cms_service_v1_Category_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_cms_service_v1_Category_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_Category_descriptor,
        new java.lang.String[] { "TenantId", "Title", "Description", "Thumb", "OutLink", "Views", "Icon", "Keywords", "ParentId", "Status", "CreatorId", "UpdaterId", "CreatedAt", "UpdatedAt", "DeletedAt", "Remark", "Sort", });
    internal_static_api_cms_service_v1_Article_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_cms_service_v1_Article_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_Article_descriptor,
        new java.lang.String[] { "TenantId", "Title", "Description", "Thumb", "OutLink", "Views", "Icon", "Keywords", "CategoryId", "Status", "CreatorId", "UpdaterId", "CreatedAt", "UpdatedAt", "DeletedAt", "Remark", "Sort", });
    internal_static_api_cms_service_v1_ArticleData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_cms_service_v1_ArticleData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ArticleData_descriptor,
        new java.lang.String[] { "Id", "ArticleId", "Content", "AllowComment", "CopyFrom", });
    internal_static_api_cms_service_v1_CreateCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_cms_service_v1_CreateCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_CreateCategoryRequest_descriptor,
        new java.lang.String[] { "TenantId", "Category", });
    internal_static_api_cms_service_v1_CreateCategoryReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_cms_service_v1_CreateCategoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_CreateCategoryReply_descriptor,
        new java.lang.String[] { "Ok", "Id", });
    internal_static_api_cms_service_v1_UpdateCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_cms_service_v1_UpdateCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_UpdateCategoryRequest_descriptor,
        new java.lang.String[] { "TenantId", "Category", "FieldMask", });
    internal_static_api_cms_service_v1_UpdateCategoryReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_api_cms_service_v1_UpdateCategoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_UpdateCategoryReply_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_api_cms_service_v1_DeleteCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_api_cms_service_v1_DeleteCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_DeleteCategoryRequest_descriptor,
        new java.lang.String[] { "TenantId", });
    internal_static_api_cms_service_v1_DeleteCategoryReply_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_api_cms_service_v1_DeleteCategoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_DeleteCategoryReply_descriptor,
        new java.lang.String[] { });
    internal_static_api_cms_service_v1_GetCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_api_cms_service_v1_GetCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_GetCategoryRequest_descriptor,
        new java.lang.String[] { "TenantId", });
    internal_static_api_cms_service_v1_GetCategoryReply_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_api_cms_service_v1_GetCategoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_GetCategoryReply_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_api_cms_service_v1_ListCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_api_cms_service_v1_ListCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListCategoryRequest_descriptor,
        new java.lang.String[] { "TenantId", });
    internal_static_api_cms_service_v1_ListCategoryReply_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_api_cms_service_v1_ListCategoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListCategoryReply_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", "List", "TotalSize", "TotalPage", "ShowFieldMask", });
    internal_static_api_cms_service_v1_CreateArticleRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_api_cms_service_v1_CreateArticleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_CreateArticleRequest_descriptor,
        new java.lang.String[] { "TenantId", "Article", });
    internal_static_api_cms_service_v1_CreateArticleReply_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_api_cms_service_v1_CreateArticleReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_CreateArticleReply_descriptor,
        new java.lang.String[] { "TenantId", "Id", });
    internal_static_api_cms_service_v1_UpdateArticleRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_api_cms_service_v1_UpdateArticleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_UpdateArticleRequest_descriptor,
        new java.lang.String[] { "TenantId", "Article", "UpdateFieldMask", });
    internal_static_api_cms_service_v1_UpdateArticleReply_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_api_cms_service_v1_UpdateArticleReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_UpdateArticleReply_descriptor,
        new java.lang.String[] { "Ok", });
    internal_static_api_cms_service_v1_DeleteArticleRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_api_cms_service_v1_DeleteArticleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_DeleteArticleRequest_descriptor,
        new java.lang.String[] { "TenantId", "Ids", });
    internal_static_api_cms_service_v1_DeleteArticleReply_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_api_cms_service_v1_DeleteArticleReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_DeleteArticleReply_descriptor,
        new java.lang.String[] { "Ok", });
    internal_static_api_cms_service_v1_GetArticleRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_api_cms_service_v1_GetArticleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_GetArticleRequest_descriptor,
        new java.lang.String[] { "TenantId", "Id", "ShowFieldMask", });
    internal_static_api_cms_service_v1_GetArticleReply_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_api_cms_service_v1_GetArticleReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_GetArticleReply_descriptor,
        new java.lang.String[] { "Article", "ShowFieldMask", });
    internal_static_api_cms_service_v1_ListArticleRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_api_cms_service_v1_ListArticleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListArticleRequest_descriptor,
        new java.lang.String[] { "TenantId", "ShowFieldMask", });
    internal_static_api_cms_service_v1_ListArticleReply_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_api_cms_service_v1_ListArticleReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListArticleReply_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", "List", "TotalSize", "TotalPage", "ShowFieldMask", });
    internal_static_api_cms_service_v1_ListCategoryByPidRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_api_cms_service_v1_ListCategoryByPidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListCategoryByPidRequest_descriptor,
        new java.lang.String[] { "TenantId", "ParentId", "ShowFieldMask", });
    internal_static_api_cms_service_v1_ListCategoryByPidReply_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_api_cms_service_v1_ListCategoryByPidReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListCategoryByPidReply_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", "List", "TotalSize", "TotalPage", "ShowFieldMask", });
    internal_static_api_cms_service_v1_ListArticleByCidRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_api_cms_service_v1_ListArticleByCidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListArticleByCidRequest_descriptor,
        new java.lang.String[] { "TenantId", "CategoryId", "ShowFieldMask", });
    internal_static_api_cms_service_v1_ListArticleByCidReply_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_api_cms_service_v1_ListArticleByCidReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_ListArticleByCidReply_descriptor,
        new java.lang.String[] { "PageNo", "PageSize", "List", "TotalSize", "TotalPage", "ShowFieldMask", });
    internal_static_api_cms_service_v1_GetArticleDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_api_cms_service_v1_GetArticleDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_GetArticleDataRequest_descriptor,
        new java.lang.String[] { "TenantId", "Id", "ShowFieldMask", });
    internal_static_api_cms_service_v1_GetArticleDataReply_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_api_cms_service_v1_GetArticleDataReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_cms_service_v1_GetArticleDataReply_descriptor,
        new java.lang.String[] { "ArticleData", "ShowFieldMask", });
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
