// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface CreateArticleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.CreateArticleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant_id = 1;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 1;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>.api.cms.service.v1.Article article = 2;</code>
   * @return Whether the article field is set.
   */
  boolean hasArticle();
  /**
   * <code>.api.cms.service.v1.Article article = 2;</code>
   * @return The article.
   */
  api.cms.service.v1.Article getArticle();
  /**
   * <code>.api.cms.service.v1.Article article = 2;</code>
   */
  api.cms.service.v1.ArticleOrBuilder getArticleOrBuilder();
}
