// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface CreateCategoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.CreateCategoryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
