// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface DeleteArticleReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.DeleteArticleReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();
}
