// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface DeleteArticleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.DeleteArticleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tenant_id = 1;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 1;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string ids = 2;</code>
   * @return The ids.
   */
  java.lang.String getIds();
  /**
   * <code>string ids = 2;</code>
   * @return The bytes for ids.
   */
  com.google.protobuf.ByteString
      getIdsBytes();
}
