// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface DeleteCategoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.DeleteCategoryReply)
    com.google.protobuf.MessageOrBuilder {
}
