// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

/**
 * Protobuf type {@code api.cms.service.v1.GetArticleReply}
 */
public final class GetArticleReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.cms.service.v1.GetArticleReply)
    GetArticleReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetArticleReply.newBuilder() to construct.
  private GetArticleReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetArticleReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetArticleReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetArticleReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            api.cms.service.v1.Article.Builder subBuilder = null;
            if (article_ != null) {
              subBuilder = article_.toBuilder();
            }
            article_ = input.readMessage(api.cms.service.v1.Article.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(article_);
              article_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.FieldMask.Builder subBuilder = null;
            if (showFieldMask_ != null) {
              subBuilder = showFieldMask_.toBuilder();
            }
            showFieldMask_ = input.readMessage(com.google.protobuf.FieldMask.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(showFieldMask_);
              showFieldMask_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_GetArticleReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_GetArticleReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.cms.service.v1.GetArticleReply.class, api.cms.service.v1.GetArticleReply.Builder.class);
  }

  public static final int ARTICLE_FIELD_NUMBER = 1;
  private api.cms.service.v1.Article article_;
  /**
   * <code>.api.cms.service.v1.Article article = 1;</code>
   * @return Whether the article field is set.
   */
  @java.lang.Override
  public boolean hasArticle() {
    return article_ != null;
  }
  /**
   * <code>.api.cms.service.v1.Article article = 1;</code>
   * @return The article.
   */
  @java.lang.Override
  public api.cms.service.v1.Article getArticle() {
    return article_ == null ? api.cms.service.v1.Article.getDefaultInstance() : article_;
  }
  /**
   * <code>.api.cms.service.v1.Article article = 1;</code>
   */
  @java.lang.Override
  public api.cms.service.v1.ArticleOrBuilder getArticleOrBuilder() {
    return getArticle();
  }

  public static final int SHOW_FIELD_MASK_FIELD_NUMBER = 2;
  private com.google.protobuf.FieldMask showFieldMask_;
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
   * @return Whether the showFieldMask field is set.
   */
  @java.lang.Override
  public boolean hasShowFieldMask() {
    return showFieldMask_ != null;
  }
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
   * @return The showFieldMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getShowFieldMask() {
    return showFieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : showFieldMask_;
  }
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getShowFieldMaskOrBuilder() {
    return getShowFieldMask();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (article_ != null) {
      output.writeMessage(1, getArticle());
    }
    if (showFieldMask_ != null) {
      output.writeMessage(2, getShowFieldMask());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (article_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getArticle());
    }
    if (showFieldMask_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getShowFieldMask());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.cms.service.v1.GetArticleReply)) {
      return super.equals(obj);
    }
    api.cms.service.v1.GetArticleReply other = (api.cms.service.v1.GetArticleReply) obj;

    if (hasArticle() != other.hasArticle()) return false;
    if (hasArticle()) {
      if (!getArticle()
          .equals(other.getArticle())) return false;
    }
    if (hasShowFieldMask() != other.hasShowFieldMask()) return false;
    if (hasShowFieldMask()) {
      if (!getShowFieldMask()
          .equals(other.getShowFieldMask())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasArticle()) {
      hash = (37 * hash) + ARTICLE_FIELD_NUMBER;
      hash = (53 * hash) + getArticle().hashCode();
    }
    if (hasShowFieldMask()) {
      hash = (37 * hash) + SHOW_FIELD_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getShowFieldMask().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.cms.service.v1.GetArticleReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.cms.service.v1.GetArticleReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.GetArticleReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.GetArticleReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.cms.service.v1.GetArticleReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.cms.service.v1.GetArticleReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.cms.service.v1.GetArticleReply)
      api.cms.service.v1.GetArticleReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_GetArticleReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_GetArticleReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.cms.service.v1.GetArticleReply.class, api.cms.service.v1.GetArticleReply.Builder.class);
    }

    // Construct using api.cms.service.v1.GetArticleReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (articleBuilder_ == null) {
        article_ = null;
      } else {
        article_ = null;
        articleBuilder_ = null;
      }
      if (showFieldMaskBuilder_ == null) {
        showFieldMask_ = null;
      } else {
        showFieldMask_ = null;
        showFieldMaskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_GetArticleReply_descriptor;
    }

    @java.lang.Override
    public api.cms.service.v1.GetArticleReply getDefaultInstanceForType() {
      return api.cms.service.v1.GetArticleReply.getDefaultInstance();
    }

    @java.lang.Override
    public api.cms.service.v1.GetArticleReply build() {
      api.cms.service.v1.GetArticleReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.cms.service.v1.GetArticleReply buildPartial() {
      api.cms.service.v1.GetArticleReply result = new api.cms.service.v1.GetArticleReply(this);
      if (articleBuilder_ == null) {
        result.article_ = article_;
      } else {
        result.article_ = articleBuilder_.build();
      }
      if (showFieldMaskBuilder_ == null) {
        result.showFieldMask_ = showFieldMask_;
      } else {
        result.showFieldMask_ = showFieldMaskBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.cms.service.v1.GetArticleReply) {
        return mergeFrom((api.cms.service.v1.GetArticleReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.cms.service.v1.GetArticleReply other) {
      if (other == api.cms.service.v1.GetArticleReply.getDefaultInstance()) return this;
      if (other.hasArticle()) {
        mergeArticle(other.getArticle());
      }
      if (other.hasShowFieldMask()) {
        mergeShowFieldMask(other.getShowFieldMask());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.cms.service.v1.GetArticleReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.cms.service.v1.GetArticleReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private api.cms.service.v1.Article article_;
    private com.google.protobuf.SingleFieldBuilderV3<
        api.cms.service.v1.Article, api.cms.service.v1.Article.Builder, api.cms.service.v1.ArticleOrBuilder> articleBuilder_;
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     * @return Whether the article field is set.
     */
    public boolean hasArticle() {
      return articleBuilder_ != null || article_ != null;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     * @return The article.
     */
    public api.cms.service.v1.Article getArticle() {
      if (articleBuilder_ == null) {
        return article_ == null ? api.cms.service.v1.Article.getDefaultInstance() : article_;
      } else {
        return articleBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    public Builder setArticle(api.cms.service.v1.Article value) {
      if (articleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        article_ = value;
        onChanged();
      } else {
        articleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    public Builder setArticle(
        api.cms.service.v1.Article.Builder builderForValue) {
      if (articleBuilder_ == null) {
        article_ = builderForValue.build();
        onChanged();
      } else {
        articleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    public Builder mergeArticle(api.cms.service.v1.Article value) {
      if (articleBuilder_ == null) {
        if (article_ != null) {
          article_ =
            api.cms.service.v1.Article.newBuilder(article_).mergeFrom(value).buildPartial();
        } else {
          article_ = value;
        }
        onChanged();
      } else {
        articleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    public Builder clearArticle() {
      if (articleBuilder_ == null) {
        article_ = null;
        onChanged();
      } else {
        article_ = null;
        articleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    public api.cms.service.v1.Article.Builder getArticleBuilder() {
      
      onChanged();
      return getArticleFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    public api.cms.service.v1.ArticleOrBuilder getArticleOrBuilder() {
      if (articleBuilder_ != null) {
        return articleBuilder_.getMessageOrBuilder();
      } else {
        return article_ == null ?
            api.cms.service.v1.Article.getDefaultInstance() : article_;
      }
    }
    /**
     * <code>.api.cms.service.v1.Article article = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.cms.service.v1.Article, api.cms.service.v1.Article.Builder, api.cms.service.v1.ArticleOrBuilder> 
        getArticleFieldBuilder() {
      if (articleBuilder_ == null) {
        articleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.cms.service.v1.Article, api.cms.service.v1.Article.Builder, api.cms.service.v1.ArticleOrBuilder>(
                getArticle(),
                getParentForChildren(),
                isClean());
        article_ = null;
      }
      return articleBuilder_;
    }

    private com.google.protobuf.FieldMask showFieldMask_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> showFieldMaskBuilder_;
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     * @return Whether the showFieldMask field is set.
     */
    public boolean hasShowFieldMask() {
      return showFieldMaskBuilder_ != null || showFieldMask_ != null;
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     * @return The showFieldMask.
     */
    public com.google.protobuf.FieldMask getShowFieldMask() {
      if (showFieldMaskBuilder_ == null) {
        return showFieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : showFieldMask_;
      } else {
        return showFieldMaskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    public Builder setShowFieldMask(com.google.protobuf.FieldMask value) {
      if (showFieldMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        showFieldMask_ = value;
        onChanged();
      } else {
        showFieldMaskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    public Builder setShowFieldMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (showFieldMaskBuilder_ == null) {
        showFieldMask_ = builderForValue.build();
        onChanged();
      } else {
        showFieldMaskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    public Builder mergeShowFieldMask(com.google.protobuf.FieldMask value) {
      if (showFieldMaskBuilder_ == null) {
        if (showFieldMask_ != null) {
          showFieldMask_ =
            com.google.protobuf.FieldMask.newBuilder(showFieldMask_).mergeFrom(value).buildPartial();
        } else {
          showFieldMask_ = value;
        }
        onChanged();
      } else {
        showFieldMaskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    public Builder clearShowFieldMask() {
      if (showFieldMaskBuilder_ == null) {
        showFieldMask_ = null;
        onChanged();
      } else {
        showFieldMask_ = null;
        showFieldMaskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    public com.google.protobuf.FieldMask.Builder getShowFieldMaskBuilder() {
      
      onChanged();
      return getShowFieldMaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getShowFieldMaskOrBuilder() {
      if (showFieldMaskBuilder_ != null) {
        return showFieldMaskBuilder_.getMessageOrBuilder();
      } else {
        return showFieldMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : showFieldMask_;
      }
    }
    /**
     * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        getShowFieldMaskFieldBuilder() {
      if (showFieldMaskBuilder_ == null) {
        showFieldMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getShowFieldMask(),
                getParentForChildren(),
                isClean());
        showFieldMask_ = null;
      }
      return showFieldMaskBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.cms.service.v1.GetArticleReply)
  }

  // @@protoc_insertion_point(class_scope:api.cms.service.v1.GetArticleReply)
  private static final api.cms.service.v1.GetArticleReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.cms.service.v1.GetArticleReply();
  }

  public static api.cms.service.v1.GetArticleReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetArticleReply>
      PARSER = new com.google.protobuf.AbstractParser<GetArticleReply>() {
    @java.lang.Override
    public GetArticleReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetArticleReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetArticleReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetArticleReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.cms.service.v1.GetArticleReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

