// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface GetArticleReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.GetArticleReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.cms.service.v1.Article article = 1;</code>
   * @return Whether the article field is set.
   */
  boolean hasArticle();
  /**
   * <code>.api.cms.service.v1.Article article = 1;</code>
   * @return The article.
   */
  api.cms.service.v1.Article getArticle();
  /**
   * <code>.api.cms.service.v1.Article article = 1;</code>
   */
  api.cms.service.v1.ArticleOrBuilder getArticleOrBuilder();

  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
   * @return Whether the showFieldMask field is set.
   */
  boolean hasShowFieldMask();
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
   * @return The showFieldMask.
   */
  com.google.protobuf.FieldMask getShowFieldMask();
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getShowFieldMaskOrBuilder();
}
