// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface GetCategoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.GetCategoryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.cms.service.v1.Category category = 1;</code>
   * @return Whether the category field is set.
   */
  boolean hasCategory();
  /**
   * <code>.api.cms.service.v1.Category category = 1;</code>
   * @return The category.
   */
  api.cms.service.v1.Category getCategory();
  /**
   * <code>.api.cms.service.v1.Category category = 1;</code>
   */
  api.cms.service.v1.CategoryOrBuilder getCategoryOrBuilder();
}
