// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

public interface ListArticleReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.cms.service.v1.ListArticleReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 page_no = 1;</code>
   * @return The pageNo.
   */
  long getPageNo();

  /**
   * <code>int64 page_size = 2;</code>
   * @return The pageSize.
   */
  long getPageSize();

  /**
   * <code>repeated .api.cms.service.v1.Article list = 3;</code>
   */
  java.util.List<api.cms.service.v1.Article> 
      getListList();
  /**
   * <code>repeated .api.cms.service.v1.Article list = 3;</code>
   */
  api.cms.service.v1.Article getList(int index);
  /**
   * <code>repeated .api.cms.service.v1.Article list = 3;</code>
   */
  int getListCount();
  /**
   * <code>repeated .api.cms.service.v1.Article list = 3;</code>
   */
  java.util.List<? extends api.cms.service.v1.ArticleOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .api.cms.service.v1.Article list = 3;</code>
   */
  api.cms.service.v1.ArticleOrBuilder getListOrBuilder(
      int index);

  /**
   * <code>int64 total_size = 4;</code>
   * @return The totalSize.
   */
  long getTotalSize();

  /**
   * <code>uint64 total_page = 5;</code>
   * @return The totalPage.
   */
  long getTotalPage();

  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 6;</code>
   * @return Whether the showFieldMask field is set.
   */
  boolean hasShowFieldMask();
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 6;</code>
   * @return The showFieldMask.
   */
  com.google.protobuf.FieldMask getShowFieldMask();
  /**
   * <code>.google.protobuf.FieldMask show_field_mask = 6;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getShowFieldMaskOrBuilder();
}
