// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

/**
 * Protobuf type {@code api.cms.service.v1.UpdateCategoryReply}
 */
public final class UpdateCategoryReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.cms.service.v1.UpdateCategoryReply)
    UpdateCategoryReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateCategoryReply.newBuilder() to construct.
  private UpdateCategoryReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateCategoryReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateCategoryReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateCategoryReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            api.cms.service.v1.Category.Builder subBuilder = null;
            if (category_ != null) {
              subBuilder = category_.toBuilder();
            }
            category_ = input.readMessage(api.cms.service.v1.Category.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(category_);
              category_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateCategoryReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateCategoryReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.cms.service.v1.UpdateCategoryReply.class, api.cms.service.v1.UpdateCategoryReply.Builder.class);
  }

  public static final int CATEGORY_FIELD_NUMBER = 1;
  private api.cms.service.v1.Category category_;
  /**
   * <code>.api.cms.service.v1.Category category = 1;</code>
   * @return Whether the category field is set.
   */
  @java.lang.Override
  public boolean hasCategory() {
    return category_ != null;
  }
  /**
   * <code>.api.cms.service.v1.Category category = 1;</code>
   * @return The category.
   */
  @java.lang.Override
  public api.cms.service.v1.Category getCategory() {
    return category_ == null ? api.cms.service.v1.Category.getDefaultInstance() : category_;
  }
  /**
   * <code>.api.cms.service.v1.Category category = 1;</code>
   */
  @java.lang.Override
  public api.cms.service.v1.CategoryOrBuilder getCategoryOrBuilder() {
    return getCategory();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (category_ != null) {
      output.writeMessage(1, getCategory());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (category_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCategory());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.cms.service.v1.UpdateCategoryReply)) {
      return super.equals(obj);
    }
    api.cms.service.v1.UpdateCategoryReply other = (api.cms.service.v1.UpdateCategoryReply) obj;

    if (hasCategory() != other.hasCategory()) return false;
    if (hasCategory()) {
      if (!getCategory()
          .equals(other.getCategory())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCategory()) {
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.UpdateCategoryReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.cms.service.v1.UpdateCategoryReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.cms.service.v1.UpdateCategoryReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.cms.service.v1.UpdateCategoryReply)
      api.cms.service.v1.UpdateCategoryReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateCategoryReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateCategoryReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.cms.service.v1.UpdateCategoryReply.class, api.cms.service.v1.UpdateCategoryReply.Builder.class);
    }

    // Construct using api.cms.service.v1.UpdateCategoryReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (categoryBuilder_ == null) {
        category_ = null;
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateCategoryReply_descriptor;
    }

    @java.lang.Override
    public api.cms.service.v1.UpdateCategoryReply getDefaultInstanceForType() {
      return api.cms.service.v1.UpdateCategoryReply.getDefaultInstance();
    }

    @java.lang.Override
    public api.cms.service.v1.UpdateCategoryReply build() {
      api.cms.service.v1.UpdateCategoryReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.cms.service.v1.UpdateCategoryReply buildPartial() {
      api.cms.service.v1.UpdateCategoryReply result = new api.cms.service.v1.UpdateCategoryReply(this);
      if (categoryBuilder_ == null) {
        result.category_ = category_;
      } else {
        result.category_ = categoryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.cms.service.v1.UpdateCategoryReply) {
        return mergeFrom((api.cms.service.v1.UpdateCategoryReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.cms.service.v1.UpdateCategoryReply other) {
      if (other == api.cms.service.v1.UpdateCategoryReply.getDefaultInstance()) return this;
      if (other.hasCategory()) {
        mergeCategory(other.getCategory());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.cms.service.v1.UpdateCategoryReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.cms.service.v1.UpdateCategoryReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private api.cms.service.v1.Category category_;
    private com.google.protobuf.SingleFieldBuilderV3<
        api.cms.service.v1.Category, api.cms.service.v1.Category.Builder, api.cms.service.v1.CategoryOrBuilder> categoryBuilder_;
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     * @return Whether the category field is set.
     */
    public boolean hasCategory() {
      return categoryBuilder_ != null || category_ != null;
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     * @return The category.
     */
    public api.cms.service.v1.Category getCategory() {
      if (categoryBuilder_ == null) {
        return category_ == null ? api.cms.service.v1.Category.getDefaultInstance() : category_;
      } else {
        return categoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    public Builder setCategory(api.cms.service.v1.Category value) {
      if (categoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        category_ = value;
        onChanged();
      } else {
        categoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    public Builder setCategory(
        api.cms.service.v1.Category.Builder builderForValue) {
      if (categoryBuilder_ == null) {
        category_ = builderForValue.build();
        onChanged();
      } else {
        categoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    public Builder mergeCategory(api.cms.service.v1.Category value) {
      if (categoryBuilder_ == null) {
        if (category_ != null) {
          category_ =
            api.cms.service.v1.Category.newBuilder(category_).mergeFrom(value).buildPartial();
        } else {
          category_ = value;
        }
        onChanged();
      } else {
        categoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    public Builder clearCategory() {
      if (categoryBuilder_ == null) {
        category_ = null;
        onChanged();
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    public api.cms.service.v1.Category.Builder getCategoryBuilder() {
      
      onChanged();
      return getCategoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    public api.cms.service.v1.CategoryOrBuilder getCategoryOrBuilder() {
      if (categoryBuilder_ != null) {
        return categoryBuilder_.getMessageOrBuilder();
      } else {
        return category_ == null ?
            api.cms.service.v1.Category.getDefaultInstance() : category_;
      }
    }
    /**
     * <code>.api.cms.service.v1.Category category = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.cms.service.v1.Category, api.cms.service.v1.Category.Builder, api.cms.service.v1.CategoryOrBuilder> 
        getCategoryFieldBuilder() {
      if (categoryBuilder_ == null) {
        categoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.cms.service.v1.Category, api.cms.service.v1.Category.Builder, api.cms.service.v1.CategoryOrBuilder>(
                getCategory(),
                getParentForChildren(),
                isClean());
        category_ = null;
      }
      return categoryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.cms.service.v1.UpdateCategoryReply)
  }

  // @@protoc_insertion_point(class_scope:api.cms.service.v1.UpdateCategoryReply)
  private static final api.cms.service.v1.UpdateCategoryReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.cms.service.v1.UpdateCategoryReply();
  }

  public static api.cms.service.v1.UpdateCategoryReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateCategoryReply>
      PARSER = new com.google.protobuf.AbstractParser<UpdateCategoryReply>() {
    @java.lang.Override
    public UpdateCategoryReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateCategoryReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateCategoryReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateCategoryReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.cms.service.v1.UpdateCategoryReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

