// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package api.cms.service.v1;

/**
 * Protobuf type {@code api.cms.service.v1.UpdateArticleRequest}
 */
public final class UpdateArticleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.cms.service.v1.UpdateArticleRequest)
    UpdateArticleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateArticleRequest.newBuilder() to construct.
  private UpdateArticleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateArticleRequest() {
    tenantId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateArticleRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateArticleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tenantId_ = s;
            break;
          }
          case 18: {
            api.cms.service.v1.Article.Builder subBuilder = null;
            if (article_ != null) {
              subBuilder = article_.toBuilder();
            }
            article_ = input.readMessage(api.cms.service.v1.Article.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(article_);
              article_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.FieldMask.Builder subBuilder = null;
            if (updateFieldMask_ != null) {
              subBuilder = updateFieldMask_.toBuilder();
            }
            updateFieldMask_ = input.readMessage(com.google.protobuf.FieldMask.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updateFieldMask_);
              updateFieldMask_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateArticleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateArticleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            api.cms.service.v1.UpdateArticleRequest.class, api.cms.service.v1.UpdateArticleRequest.Builder.class);
  }

  public static final int TENANT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object tenantId_;
  /**
   * <code>string tenant_id = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 1;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARTICLE_FIELD_NUMBER = 2;
  private api.cms.service.v1.Article article_;
  /**
   * <code>.api.cms.service.v1.Article article = 2;</code>
   * @return Whether the article field is set.
   */
  @java.lang.Override
  public boolean hasArticle() {
    return article_ != null;
  }
  /**
   * <code>.api.cms.service.v1.Article article = 2;</code>
   * @return The article.
   */
  @java.lang.Override
  public api.cms.service.v1.Article getArticle() {
    return article_ == null ? api.cms.service.v1.Article.getDefaultInstance() : article_;
  }
  /**
   * <code>.api.cms.service.v1.Article article = 2;</code>
   */
  @java.lang.Override
  public api.cms.service.v1.ArticleOrBuilder getArticleOrBuilder() {
    return getArticle();
  }

  public static final int UPDATE_FIELD_MASK_FIELD_NUMBER = 3;
  private com.google.protobuf.FieldMask updateFieldMask_;
  /**
   * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
   * @return Whether the updateFieldMask field is set.
   */
  @java.lang.Override
  public boolean hasUpdateFieldMask() {
    return updateFieldMask_ != null;
  }
  /**
   * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
   * @return The updateFieldMask.
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getUpdateFieldMask() {
    return updateFieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateFieldMask_;
  }
  /**
   * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMaskOrBuilder getUpdateFieldMaskOrBuilder() {
    return getUpdateFieldMask();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tenantId_);
    }
    if (article_ != null) {
      output.writeMessage(2, getArticle());
    }
    if (updateFieldMask_ != null) {
      output.writeMessage(3, getUpdateFieldMask());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tenantId_);
    }
    if (article_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getArticle());
    }
    if (updateFieldMask_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUpdateFieldMask());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof api.cms.service.v1.UpdateArticleRequest)) {
      return super.equals(obj);
    }
    api.cms.service.v1.UpdateArticleRequest other = (api.cms.service.v1.UpdateArticleRequest) obj;

    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (hasArticle() != other.hasArticle()) return false;
    if (hasArticle()) {
      if (!getArticle()
          .equals(other.getArticle())) return false;
    }
    if (hasUpdateFieldMask() != other.hasUpdateFieldMask()) return false;
    if (hasUpdateFieldMask()) {
      if (!getUpdateFieldMask()
          .equals(other.getUpdateFieldMask())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    if (hasArticle()) {
      hash = (37 * hash) + ARTICLE_FIELD_NUMBER;
      hash = (53 * hash) + getArticle().hashCode();
    }
    if (hasUpdateFieldMask()) {
      hash = (37 * hash) + UPDATE_FIELD_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateFieldMask().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static api.cms.service.v1.UpdateArticleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(api.cms.service.v1.UpdateArticleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.cms.service.v1.UpdateArticleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.cms.service.v1.UpdateArticleRequest)
      api.cms.service.v1.UpdateArticleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateArticleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateArticleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.cms.service.v1.UpdateArticleRequest.class, api.cms.service.v1.UpdateArticleRequest.Builder.class);
    }

    // Construct using api.cms.service.v1.UpdateArticleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tenantId_ = "";

      if (articleBuilder_ == null) {
        article_ = null;
      } else {
        article_ = null;
        articleBuilder_ = null;
      }
      if (updateFieldMaskBuilder_ == null) {
        updateFieldMask_ = null;
      } else {
        updateFieldMask_ = null;
        updateFieldMaskBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return api.cms.service.v1.CmsOuterClass.internal_static_api_cms_service_v1_UpdateArticleRequest_descriptor;
    }

    @java.lang.Override
    public api.cms.service.v1.UpdateArticleRequest getDefaultInstanceForType() {
      return api.cms.service.v1.UpdateArticleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public api.cms.service.v1.UpdateArticleRequest build() {
      api.cms.service.v1.UpdateArticleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public api.cms.service.v1.UpdateArticleRequest buildPartial() {
      api.cms.service.v1.UpdateArticleRequest result = new api.cms.service.v1.UpdateArticleRequest(this);
      result.tenantId_ = tenantId_;
      if (articleBuilder_ == null) {
        result.article_ = article_;
      } else {
        result.article_ = articleBuilder_.build();
      }
      if (updateFieldMaskBuilder_ == null) {
        result.updateFieldMask_ = updateFieldMask_;
      } else {
        result.updateFieldMask_ = updateFieldMaskBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof api.cms.service.v1.UpdateArticleRequest) {
        return mergeFrom((api.cms.service.v1.UpdateArticleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(api.cms.service.v1.UpdateArticleRequest other) {
      if (other == api.cms.service.v1.UpdateArticleRequest.getDefaultInstance()) return this;
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (other.hasArticle()) {
        mergeArticle(other.getArticle());
      }
      if (other.hasUpdateFieldMask()) {
        mergeUpdateFieldMask(other.getUpdateFieldMask());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      api.cms.service.v1.UpdateArticleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (api.cms.service.v1.UpdateArticleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 1;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private api.cms.service.v1.Article article_;
    private com.google.protobuf.SingleFieldBuilderV3<
        api.cms.service.v1.Article, api.cms.service.v1.Article.Builder, api.cms.service.v1.ArticleOrBuilder> articleBuilder_;
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     * @return Whether the article field is set.
     */
    public boolean hasArticle() {
      return articleBuilder_ != null || article_ != null;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     * @return The article.
     */
    public api.cms.service.v1.Article getArticle() {
      if (articleBuilder_ == null) {
        return article_ == null ? api.cms.service.v1.Article.getDefaultInstance() : article_;
      } else {
        return articleBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    public Builder setArticle(api.cms.service.v1.Article value) {
      if (articleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        article_ = value;
        onChanged();
      } else {
        articleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    public Builder setArticle(
        api.cms.service.v1.Article.Builder builderForValue) {
      if (articleBuilder_ == null) {
        article_ = builderForValue.build();
        onChanged();
      } else {
        articleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    public Builder mergeArticle(api.cms.service.v1.Article value) {
      if (articleBuilder_ == null) {
        if (article_ != null) {
          article_ =
            api.cms.service.v1.Article.newBuilder(article_).mergeFrom(value).buildPartial();
        } else {
          article_ = value;
        }
        onChanged();
      } else {
        articleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    public Builder clearArticle() {
      if (articleBuilder_ == null) {
        article_ = null;
        onChanged();
      } else {
        article_ = null;
        articleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    public api.cms.service.v1.Article.Builder getArticleBuilder() {
      
      onChanged();
      return getArticleFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    public api.cms.service.v1.ArticleOrBuilder getArticleOrBuilder() {
      if (articleBuilder_ != null) {
        return articleBuilder_.getMessageOrBuilder();
      } else {
        return article_ == null ?
            api.cms.service.v1.Article.getDefaultInstance() : article_;
      }
    }
    /**
     * <code>.api.cms.service.v1.Article article = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        api.cms.service.v1.Article, api.cms.service.v1.Article.Builder, api.cms.service.v1.ArticleOrBuilder> 
        getArticleFieldBuilder() {
      if (articleBuilder_ == null) {
        articleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            api.cms.service.v1.Article, api.cms.service.v1.Article.Builder, api.cms.service.v1.ArticleOrBuilder>(
                getArticle(),
                getParentForChildren(),
                isClean());
        article_ = null;
      }
      return articleBuilder_;
    }

    private com.google.protobuf.FieldMask updateFieldMask_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> updateFieldMaskBuilder_;
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     * @return Whether the updateFieldMask field is set.
     */
    public boolean hasUpdateFieldMask() {
      return updateFieldMaskBuilder_ != null || updateFieldMask_ != null;
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     * @return The updateFieldMask.
     */
    public com.google.protobuf.FieldMask getUpdateFieldMask() {
      if (updateFieldMaskBuilder_ == null) {
        return updateFieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateFieldMask_;
      } else {
        return updateFieldMaskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    public Builder setUpdateFieldMask(com.google.protobuf.FieldMask value) {
      if (updateFieldMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateFieldMask_ = value;
        onChanged();
      } else {
        updateFieldMaskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    public Builder setUpdateFieldMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (updateFieldMaskBuilder_ == null) {
        updateFieldMask_ = builderForValue.build();
        onChanged();
      } else {
        updateFieldMaskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    public Builder mergeUpdateFieldMask(com.google.protobuf.FieldMask value) {
      if (updateFieldMaskBuilder_ == null) {
        if (updateFieldMask_ != null) {
          updateFieldMask_ =
            com.google.protobuf.FieldMask.newBuilder(updateFieldMask_).mergeFrom(value).buildPartial();
        } else {
          updateFieldMask_ = value;
        }
        onChanged();
      } else {
        updateFieldMaskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    public Builder clearUpdateFieldMask() {
      if (updateFieldMaskBuilder_ == null) {
        updateFieldMask_ = null;
        onChanged();
      } else {
        updateFieldMask_ = null;
        updateFieldMaskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    public com.google.protobuf.FieldMask.Builder getUpdateFieldMaskBuilder() {
      
      onChanged();
      return getUpdateFieldMaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getUpdateFieldMaskOrBuilder() {
      if (updateFieldMaskBuilder_ != null) {
        return updateFieldMaskBuilder_.getMessageOrBuilder();
      } else {
        return updateFieldMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : updateFieldMask_;
      }
    }
    /**
     * <code>.google.protobuf.FieldMask update_field_mask = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        getUpdateFieldMaskFieldBuilder() {
      if (updateFieldMaskBuilder_ == null) {
        updateFieldMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getUpdateFieldMask(),
                getParentForChildren(),
                isClean());
        updateFieldMask_ = null;
      }
      return updateFieldMaskBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.cms.service.v1.UpdateArticleRequest)
  }

  // @@protoc_insertion_point(class_scope:api.cms.service.v1.UpdateArticleRequest)
  private static final api.cms.service.v1.UpdateArticleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new api.cms.service.v1.UpdateArticleRequest();
  }

  public static api.cms.service.v1.UpdateArticleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateArticleRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateArticleRequest>() {
    @java.lang.Override
    public UpdateArticleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateArticleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateArticleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateArticleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public api.cms.service.v1.UpdateArticleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

